/**
 * Gallery Items Data
 * ──────────────────────────────────────────────────────────────
 * High-resolution imagery representing VR Tax CPA LLC's Irving, TX
 * office, executive client consultations, tax planning workshops,
 * firm celebrations, and community outreach.
 */

export const galleryCategories = [
  { id: "all", name: "All Moments" },
  { id: "office", name: "Office & Firm" },
  { id: "consultation", name: "Client Advisory" },
  { id: "events", name: "Workshops & Events" },
  { id: "team", name: "Team & Culture" },
  { id: "community", name: "Community Outreach" },
];

export const galleryItems = [
  {
    id: "gal-1",
    title: "Irving Executive Client Lounge",
    category: "Office & Firm",
    categoryId: "office",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80",
    date: "January 2026",
    location: "3035 Ivy Hill Lane, Irving, TX",
    description: "Our dedicated consultation suite designed for comfortable, confidential discussions on tax planning and entity structuring.",
  },
  {
    id: "gal-2",
    title: "Strategic Tax Planning Session",
    category: "Client Advisory",
    categoryId: "consultation",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80",
    date: "February 2026",
    location: "Irving HQ Conference Room",
    description: "One-on-one advisory session with a small business founder reviewing 2026 S-Corporation tax savings and quarterly estimates.",
  },
  {
    id: "gal-3",
    title: "Texas Small Business Tax Workshop",
    category: "Workshops & Events",
    categoryId: "events",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=600&q=80",
    date: "December 2025",
    location: "Dallas Metro Business Center",
    description: "Hosting our annual proactive year-end planning seminar for DFW entrepreneurs, covering Section 179 and retirement optimization.",
  },
  {
    id: "gal-4",
    title: "Collaborative Financial Review Desk",
    category: "Office & Firm",
    categoryId: "office",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80",
    date: "November 2025",
    location: "VR Tax CPA Practice Floor",
    description: "Our accounting and payroll leads collaborating on multi-entity financial statements and reconciliation reviews.",
  },
  {
    id: "gal-5",
    title: "Community Outreach & Service Day",
    category: "Community Outreach",
    categoryId: "community",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80",
    date: "October 2025",
    location: "DFW Community Food Drive",
    description: "Giving back to the local North Texas community — active volunteering and community support are foundational values at VR Tax CPA LLC.",
  },
  {
    id: "gal-6",
    title: "Fractional CFO & Cash Flow Modeling",
    category: "Client Advisory",
    categoryId: "consultation",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=600&q=80",
    date: "January 2026",
    location: "Client Boardroom, Dallas, TX",
    description: "Presenting a 12-month dynamic financial forecast, KPI dashboard, and burn-rate reduction model for a scaling tech startup.",
  },
  {
    id: "gal-7",
    title: "Team Achievement & Tax Season Celebration",
    category: "Team & Culture",
    categoryId: "team",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=600&q=80",
    date: "May 2025",
    location: "Irving, TX",
    description: "Celebrating our team's hard work, record client satisfaction scores, and successful tax season completion with dinner and awards.",
  },
  {
    id: "gal-8",
    title: "Digital Document Security & TaxDome Portal Hub",
    category: "Office & Firm",
    categoryId: "office",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80",
    date: "February 2026",
    location: "Cybersecurity & Data Center",
    description: "State-of-the-art encrypted infrastructure ensuring bank-grade protection for all sensitive IRS returns and client financials.",
  },
  {
    id: "gal-9",
    title: "Women in Accounting & Finance Panel",
    category: "Workshops & Events",
    categoryId: "events",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    date: "August 2025",
    location: "Texas Society of CPAs Forum",
    description: "CEO Vetha Ram speaking on modern CPA practices, AI in bookkeeping, and building long-term client trust through proactive guidance.",
  },
  {
    id: "gal-10",
    title: "Client Partnership Milestones",
    category: "Client Advisory",
    categoryId: "consultation",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=600&q=80",
    date: "December 2025",
    location: "Executive Suites, Las Colinas, TX",
    description: "Marking 5-year relationship milestones with healthcare practice owners and multi-unit franchises who count on VR Tax CPA LLC.",
  },
  {
    id: "gal-11",
    title: "Continuous Professional Education (CPE)",
    category: "Team & Culture",
    categoryId: "team",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=600&q=80",
    date: "September 2025",
    location: "Irving Training Room",
    description: "Our team stays ahead of IRS statutory updates, Texas state tax statutes, and advanced payroll regulations through regular masterclasses.",
  },
  {
    id: "gal-12",
    title: "ISKCON Dallas Community Volunteering",
    category: "Community Outreach",
    categoryId: "community",
    image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=600&q=80",
    date: "July 2025",
    location: "Dallas Cultural & Community Center",
    description: "Firm volunteers participating in community meal services and festival programs, celebrating culture, compassion, and unity.",
  },
];
