import { blogPosts } from "./blogData";

export const initialSiteData = {
  contactInfo: {
    officeTitle: "VR Tax CPA LLC — Irving Office",
    address: "3035 Ivy Hill Lane, Irving, TX 75063",
    phone: "(469) 471-6580",
    phoneRaw: "+14694716580",
    email: "info@vrtaxcpa.com",
    hours: "Mon–Fri: 9:00 AM – 5:30 PM CST",
    tagline: "Reliable partners in your growth.",
    mapUrl: "https://maps.google.com/maps?q=3035+Ivy+Hill+Lane,+Irving,+TX+75063&t=&z=15&ie=UTF8&iwloc=&output=embed",
  },
  socialLinks: [
    { id: "instagram", name: "Instagram", url: "https://instagram.com/vstaxcpa", enabled: true },
    { id: "facebook", name: "Facebook", url: "https://facebook.com/Vstaxcpallc", enabled: true },
    { id: "linkedin", name: "LinkedIn", url: "https://linkedin.com/company/vstaxcpa", enabled: true },
    { id: "yelp", name: "Yelp", url: "https://yelp.com/biz/vs-tax-cpa", enabled: true },
  ],
  founder: {
    name: "Vetha Ram, CPA",
    displayName: "Vetha Ram",
    title: "CPA · CA · Founder & CEO",
    experienceYears: 13,
    experienceLabel: "Years Experience",
    image: "/ceo.jpeg",
    bio: "Strategic tax planning, proactive compliance, and personalized accounting advisory designed to give business owners confidence and peace of mind.",
    activeSocials: ["instagram", "facebook", "linkedin"],
    paragraphs: [
      `"Vetha Ram, CPA", is the Founder and CEO of "VR Tax CPA LLC". With "13 years of comprehensive accounting experience" including "10 years of specialized tax expertise", she partners with business owners and individuals to navigate tax complexities with precision, clarity, and peace of mind.`,
      `Her dual qualification as a "Texas State Board Licensed CPA" and a "Chartered Accountant (India)" brings a rigorous, global analytical perspective to every client engagement. She treats each client's business with the dedication and attention of a trusted partner—never as a file number or transaction. Every relationship is built on integrity, accuracy, and genuine care.`,
      `Guided by the principle of serving with unwavering dedication, her commitment is simple: to lift financial stress so clients can focus wholeheartedly on scaling their businesses and enjoying their lives.`
    ],
    quote: `Outside the firm, she is an active volunteer at the ISKCON Dallas Temple and cherishes spending time cooking, traveling, and being with her husband and their two boys. For those seeking an advisor who truly listens and stands by their side year-round, her doors are always open.`,
    credentials: [
      "Licensed CPA — Texas State Board of Public Accountancy",
      "Chartered Accountant (CA) — Institute of Chartered Accountants of India (ICAI)",
      "13 Years of Comprehensive Accounting & Financial Management Experience",
      "10 Years of Dedicated Tax Planning, Compliance & Advisory Specialization",
      "Deep Expertise in Business Tax Strategy, Entity Structuring & IRS Relations",
      "Active Volunteer & Community Contributor at ISKCON Dallas",
    ],
  },
  team: [
    {
      id: "team-1",
      name: "Eleanor Pena",
      role: "Operations Head",
      bg: "bg-[#2D5A27]",
      bgColor: "#2D5A27",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-2",
      name: "Cameron William",
      role: "Marketing & Tax Lead",
      bg: "bg-[#4A6B22]",
      bgColor: "#4A6B22",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-3",
      name: "Robert Fox",
      role: "Business Director",
      bg: "bg-[#1E3A24]",
      bgColor: "#1E3A24",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-4",
      name: "Dianne Russell",
      role: "Senior Tax Accountant",
      bg: "bg-[#9CB05A]",
      bgColor: "#9CB05A",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-5",
      name: "Jenny Wilson",
      role: "Payroll & Compliance Lead",
      bg: "bg-[#3D6B35]",
      bgColor: "#3D6B35",
      image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-6",
      name: "Guy Hawkins",
      role: "Advisory & CFO Manager",
      bg: "bg-[#28572E]",
      bgColor: "#28572E",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    },
  ],
  testimonials: [
    {
      id: "test-1",
      name: "Marcus T.",
      desig: "Real Estate Investor · Irving, TX",
      initials: "MT",
      rating: 5,
      industry: "Real Estate",
      desc: "Vethavalli saved me tens of thousands in taxes by correctly structuring my rental properties and recommending a cost segregation study. She explained everything clearly and was available whenever I had questions. I've already referred three other investors to VR Tax CPA LLC.",
    },
    {
      id: "test-2",
      name: "Dr. Priya N.",
      desig: "Dentist · Owner, Bright Smiles Dental",
      initials: "PN",
      rating: 5,
      industry: "Dental Practice",
      desc: "Running a dental practice is already overwhelming — dealing with taxes on top of that was a nightmare until I found VR Tax CPA LLC. Vethavalli set up our payroll, organized our books, and reduced our tax liability significantly through proper S-Corp structuring. She's an absolute gem.",
    },
    {
      id: "test-3",
      name: "Alex R.",
      desig: "Co-Founder · SaaS Startup · Dallas, TX",
      initials: "AR",
      rating: 5,
      industry: "IT & Tech",
      desc: "As a tech startup founder, I needed a CPA who understands the intersection of tech, equity compensation, and growth planning. Vethavalli built us a cash flow model, helped with our entity election, and keeps our quarterly taxes on track. She's become a true strategic partner for our business.",
    },
    {
      id: "test-4",
      name: "Lisa M.",
      desig: "Restaurant Owner · Fort Worth, TX",
      initials: "LM",
      rating: 5,
      industry: "Restaurants",
      desc: "I had back taxes and unfiled returns that were keeping me up at night. VR Tax CPA LLC handled everything — they filed all the back returns, negotiated with the IRS, and got my penalties abated. Now my books are clean and my sales tax is filed on time every month. I couldn't be more relieved.",
    },
    {
      id: "test-5",
      name: "Ryan K.",
      desig: "General Contractor · DFW Area",
      initials: "RK",
      rating: 5,
      industry: "Contractors",
      desc: "Before VR Tax CPA LLC, I was leaving money on the table every year. Vethavalli found deductions I'd never claimed — home office, vehicle, tools, and retirement contributions. My tax bill dropped by over $12,000 last year. Wish I'd found her sooner!",
    },
  ],
  blogs: blogPosts,
  inquiries: [
    {
      id: "inq-101",
      name: "David Miller",
      company: "Miller Logistics LLC",
      email: "david@millerlogistics.com",
      phone: "(214) 555-0192",
      service: "Business Entity Formation (LLC / S-Corp)",
      message: "Looking to convert our LLC to an S-Corp for the upcoming fiscal year. Would like a consultation on tax savings.",
      date: "2026-09-16T10:30:00Z",
      status: "new",
    },
    {
      id: "inq-102",
      name: "Sarah Jenkins",
      company: "Bloom Health Clinic",
      email: "sarah@bloomhealth.org",
      phone: "(469) 555-0841",
      service: "Payroll Support (Setup & Training)",
      message: "We need comprehensive payroll setup and bookkeeping cleanup for our 8 employees.",
      date: "2026-09-15T14:15:00Z",
      status: "replied",
    },
  ],
  adminSettings: {
    username: "admin",
    passcode: "VRtaxcpa@2026",
    backendApiUrl: "",
  },
};
