import { blogPosts } from "./blogData";
import { servicesData } from "./servicesData";
import { galleryItems } from "./galleryData";

export const initialSiteData = {
  contactInfo: {
    officeTitle: "VR Tax CPA LLC — Irving Office",
    address: "3035 Ivy Hill Lane, Irving, TX 75063",
    phone: "(469) 471-6580",
    phoneRaw: "+14694716580",
    email: "info@vrtaxcpa.com",
    hours: "Mon–Fri: 9:00 AM – 5:30 PM CST",
    tagline: "Reliable partners in your growth.",
    mapUrl: "https://maps.google.com/maps?q=3035+Ivy+Hill+Lane,+Irving,+TX+75063&t=&z=15&ie=UTF8&iwloc=&output=embed",
  },
  socialLinks: [
    { id: "instagram", name: "Instagram", url: "https://instagram.com/vstaxcpa", enabled: true },
    { id: "facebook", name: "Facebook", url: "https://facebook.com/Vstaxcpallc", enabled: true },
    { id: "linkedin", name: "LinkedIn", url: "https://linkedin.com/company/vstaxcpa", enabled: true },
    { id: "yelp", name: "Yelp", url: "https://yelp.com/biz/vs-tax-cpa", enabled: true },
  ],
  founder: {
    name: "Vetha Ram, CPA",
    displayName: "Vetha Ram",
    title: "CPA · CA · Founder & CEO",
    experienceYears: 13,
    experienceLabel: "Years Experience",
    image: "/ceo.jpeg",
    bio: "Strategic tax planning, proactive compliance, and personalized accounting advisory designed to give business owners confidence and peace of mind.",
    activeSocials: ["instagram", "facebook", "linkedin"],
    paragraphs: [
      `"Vetha Ram, CPA", is the Founder and CEO of "VR Tax CPA LLC". With "13 years of comprehensive accounting experience" including "10 years of specialized tax expertise", she partners with business owners and individuals to navigate tax complexities with precision, clarity, and peace of mind.`,
      `Her dual qualification as a "Texas State Board Licensed CPA" and a "Chartered Accountant (India)" brings a rigorous, global analytical perspective to every client engagement. She treats each client's business with the dedication and attention of a trusted partner—never as a file number or transaction. Every relationship is built on integrity, accuracy, and genuine care.`,
      `Guided by the principle of serving with unwavering dedication, her commitment is simple: to lift financial stress so clients can focus wholeheartedly on scaling their businesses and enjoying their lives.`
    ],
    quote: `Outside the firm, she is an active volunteer at the ISKCON Dallas Temple and cherishes spending time cooking, traveling, and being with her husband and their two boys. For those seeking an advisor who truly listens and stands by their side year-round, her doors are always open.`,
    credentials: [
      "Licensed CPA — Texas State Board of Public Accountancy",
      "Chartered Accountant (CA) — Institute of Chartered Accountants of India (ICAI)",
      "13 Years of Comprehensive Accounting & Financial Management Experience",
      "10 Years of Dedicated Tax Planning, Compliance & Advisory Specialization",
      "Deep Expertise in Business Tax Strategy, Entity Structuring & IRS Relations",
      "Active Volunteer & Community Contributor at ISKCON Dallas",
    ],
  },
  team: [
    {
      id: "team-1",
      name: "Eleanor Pena",
      role: "Operations Head",
      bg: "bg-[#2D5A27]",
      bgColor: "#2D5A27",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-2",
      name: "Cameron William",
      role: "Marketing & Tax Lead",
      bg: "bg-[#4A6B22]",
      bgColor: "#4A6B22",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-3",
      name: "Robert Fox",
      role: "Business Director",
      bg: "bg-[#1E3A24]",
      bgColor: "#1E3A24",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-4",
      name: "Dianne Russell",
      role: "Senior Tax Accountant",
      bg: "bg-[#9CB05A]",
      bgColor: "#9CB05A",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-5",
      name: "Jenny Wilson",
      role: "Payroll & Compliance Lead",
      bg: "bg-[#3D6B35]",
      bgColor: "#3D6B35",
      image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "team-6",
      name: "Guy Hawkins",
      role: "Advisory & CFO Manager",
      bg: "bg-[#28572E]",
      bgColor: "#28572E",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    },
  ],
  testimonials: [
    {
      id: "test-1",
      name: "Marcus T.",
      desig: "Real Estate Investor · Irving, TX",
      initials: "MT",
      rating: 5,
      industry: "Real Estate",
      desc: "Vethavalli saved me tens of thousands in taxes by correctly structuring my rental properties and recommending a cost segregation study. She explained everything clearly and was available whenever I had questions. I've already referred three other investors to VR Tax CPA LLC.",
    },
    {
      id: "test-2",
      name: "Dr. Priya N.",
      desig: "Dentist · Owner, Bright Smiles Dental",
      initials: "PN",
      rating: 5,
      industry: "Dental Practice",
      desc: "Running a dental practice is already overwhelming — dealing with taxes on top of that was a nightmare until I found VR Tax CPA LLC. Vethavalli set up our payroll, organized our books, and reduced our tax liability significantly through proper S-Corp structuring. She's an absolute gem.",
    },
    {
      id: "test-3",
      name: "Alex R.",
      desig: "Co-Founder · SaaS Startup · Dallas, TX",
      initials: "AR",
      rating: 5,
      industry: "IT & Tech",
      desc: "As a tech startup founder, I needed a CPA who understands the intersection of tech, equity compensation, and growth planning. Vethavalli built us a cash flow model, helped with our entity election, and keeps our quarterly taxes on track. She's become a true strategic partner for our business.",
    },
    {
      id: "test-4",
      name: "Lisa M.",
      desig: "Restaurant Owner · Fort Worth, TX",
      initials: "LM",
      rating: 5,
      industry: "Restaurants",
      desc: "I had back taxes and unfiled returns that were keeping me up at night. VR Tax CPA LLC handled everything — they filed all the back returns, negotiated with the IRS, and got my penalties abated. Now my books are clean and my sales tax is filed on time every month. I couldn't be more relieved.",
    },
    {
      id: "test-5",
      name: "Ryan K.",
      desig: "General Contractor · DFW Area",
      initials: "RK",
      rating: 5,
      industry: "Contractors",
      desc: "Before VR Tax CPA LLC, I was leaving money on the table every year. Vethavalli found deductions I'd never claimed — home office, vehicle, tools, and retirement contributions. My tax bill dropped by over $12,000 last year. Wish I'd found her sooner!",
    },
  ],
  blogs: blogPosts,
  services: servicesData,
  homeServices: [
    {
      id: "hs-1",
      no: "01",
      title: "Tax Compliance",
      desc: "Accurate and timely federal and Texas tax return preparation and filing for individuals, businesses, trusts, and exempt organizations.",
      slug: "tax-compliance",
    },
    {
      id: "hs-2",
      no: "02",
      title: "Tax Planning & Advisory",
      desc: "Proactive year-round tax planning and entity structuring to optimize tax obligations and prevent last-minute filing surprises.",
      slug: "tax-planning",
    },
    {
      id: "hs-3",
      no: "03",
      title: "Business Entity Formation",
      desc: "Advisory on entity classification (LLC, S-Corp, C-Corp), Texas state formation filings, EIN setup, and S-Corp tax elections.",
      slug: "business-formation",
    },
    {
      id: "hs-4",
      no: "04",
      title: "Payroll Support",
      desc: "We set up and train your team to manage payroll through partner platforms like QuickBooks, ensuring compliant withholding configuration.",
      slug: "payroll-services",
    },
    {
      id: "hs-5",
      no: "05",
      title: "Accounting Services",
      desc: "Monthly and quarterly bookkeeping, bank reconciliations, management financials, and year-end ledger organization.",
      slug: "accounting-services",
    },
    {
      id: "hs-6",
      no: "06",
      title: "Fractional CFO",
      desc: "Cash flow modeling, KPI tracking dashboards, and internal management budgeting — tailored for growing businesses.",
      slug: "fractional-cfo",
    },
    {
      id: "hs-7",
      no: "07",
      title: "IRS Representation",
      desc: "Notice response, IRS representation, penalty abatement review, and unfiled prior-year tax return resolution.",
      slug: "irs-representation",
    },
    {
      id: "hs-8",
      no: "08",
      title: "Sales Tax & 1099",
      desc: "Texas sales tax return filings, plus year-end preparation and electronic filing of 1099s for contractors, rent, interest, and dividends.",
      slug: "sales-tax-1099",
    },
  ],
  homeFaqs: [
    {
      id: "faq-1",
      q: "What types of businesses do you work with?",
      a: "We work with small to medium-sized businesses, startups, solo entrepreneurs, S-Corps, LLCs, and professionals across healthcare & dental practices, IT & tech services, real estate, construction contractors, restaurants, and manufacturing.",
    },
    {
      id: "faq-2",
      q: "How does VR Tax CPA LLC support small businesses throughout the year?",
      a: "For our Tax Advisory clients, we proactively review and implement strategies throughout the year—analyzing allowable deductions, optimizing entity classifications, calculating quarterly estimates, and guiding tax-impacting decisions. We also offer separate Accounting services that keep your books accurate and up-to-date, ensuring your annual filing is a meticulously planned process rather than a rushed one.",
    },
    {
      id: "faq-3",
      q: "Is my financial information secure?",
      a: "Absolutely. We utilize bank-grade 256-bit encrypted digital client portals via TaxDome, secure document vaults, and adhere to strict professional standards for client confidentiality.",
    },
    {
      id: "faq-4",
      q: "Do you offer year-round support?",
      a: "Yes. We believe client service is an ongoing strategic partnership. Our team provides year-round advisory check-ins, timely deadline tracking, and responsive support whenever questions arise.",
    },
    {
      id: "faq-5",
      q: "Can you assist with IRS notices and representation?",
      a: "Yes. We assist clients with formal IRS and Texas tax notice responses, transcript reviews, penalty abatement requests where eligible under IRS criteria, and unfiled prior-year tax returns.",
    },
  ],
  gallery: galleryItems,
  partners: [
    {
      id: "partner-1",
      name: "Gusto",
      logoSrc: "/partners/logoipsum-414.png",
      category: "Payroll Partner",
    },
    {
      id: "partner-2",
      name: "QuickBooks",
      logoSrc: "/partners/logoipsum-418.png",
      category: "Accounting ProAdvisor",
    },
    {
      id: "partner-3",
      name: "Xero",
      logoSrc: "/partners/logoipsum-430.png",
      category: "Cloud Accounting",
    },
    {
      id: "partner-4",
      name: "IRS e-File",
      logoSrc: "/partners/logoipsum-432.png",
      category: "Authorized e-File Provider",
    },
    {
      id: "partner-5",
      name: "Stripe",
      logoSrc: "/partners/logoipsum-435.png",
      category: "Payment Integration",
    },
    {
      id: "partner-6",
      name: "ADP",
      logoSrc: "/partners/logoipsum-437.png",
      category: "HR & Payroll",
    },
  ],
  inquiries: [
    {
      id: "inq-101",
      name: "David Miller",
      company: "Miller Logistics LLC",
      email: "david@millerlogistics.com",
      phone: "(214) 555-0192",
      service: "Business Entity Formation (LLC / S-Corp)",
      message: "Looking to convert our LLC to an S-Corp for the upcoming fiscal year. Would like a consultation on tax savings.",
      date: "2026-09-16T10:30:00Z",
      status: "new",
    },
    {
      id: "inq-102",
      name: "Sarah Jenkins",
      company: "Bloom Health Clinic",
      email: "sarah@bloomhealth.org",
      phone: "(469) 555-0841",
      service: "Payroll Support (Setup & Training)",
      message: "We need comprehensive payroll setup and bookkeeping cleanup for our 8 employees.",
      date: "2026-09-15T14:15:00Z",
      status: "replied",
    },
  ],
  adminSettings: {
    username: "admin",
    passcode: "VRtaxcpa@2026",
    backendApiUrl: "",
  },
  legalPages: {
    termsOfService: {
      title: "Terms of Service",
      badge: "Client Agreement",
      lastUpdated: "September 2026",
      sections: [
        {
          id: "tos-1",
          heading: "1. Acceptance of Terms & Scope",
          content: "Welcome to VR Tax CPA LLC. By accessing our website (vrtaxcpa.com), booking an advisory consultation, or engaging our firm for professional tax, accounting, bookkeeping, or advisory services, you agree to comply with and be bound by these Terms of Service.",
        },
        {
          id: "tos-2",
          heading: "2. Professional Engagement Letters",
          content: "All professional tax and accounting services (including federal and state tax preparation, IRS representation, payroll support, and fractional CFO guidance) are subject to a formal, written Engagement Letter detailing the specific scope of work, client responsibilities, fee structures, and deliverables. In the event of a conflict between these general website terms and an executed Engagement Letter, the Engagement Letter shall govern.",
        },
        {
          id: "tos-3",
          heading: "3. Client Responsibilities & Secure Document Submission via TaxDome",
          content: "Accurate tax preparation and accounting depend entirely upon complete, accurate, and timely documentation provided by the client. Clients are responsible for:\n\n• Exclusive Use of TaxDome Portal: For confidentiality and data security, we do not permit or collect tax organizers or sensitive financial documents through this public website. All client organizers, tax forms, financial records, and confidential communications must be uploaded exclusively through our secure TaxDome Client Portal.\n• Providing all relevant tax forms, receipts, financial records, and disclosures before agreed deadlines.\n• Maintaining appropriate supporting documentation in accordance with IRS record-retention requirements.\n• Reviewing all completed tax returns and financial filings prior to signing electronic authorization (Form 8879).",
        },
        {
          id: "tos-4",
          heading: "4. Fees, Invoicing & Retainers",
          content: "Service fees are clearly communicated prior to engagement initiation. Invoices for tax preparation, payroll support, and accounting services are due upon receipt or as specified in your agreement. Electronic filing of returns is executed upon receipt of signed authorization and fee settlement.",
        },
        {
          id: "tos-5",
          heading: "5. Use of Third-Party Service Providers",
          content: "To deliver professional tax, accounting, bookkeeping, payroll, and advisory services, VR Tax CPA LLC may utilize secure third-party platforms and service providers. These providers assist with functions such as tax preparation software, document storage (including TaxDome), e-signature processing, payroll systems, and secure client communication. All third-party tools are selected for their security standards and are used solely to support the services you have engaged us for.",
        },
        {
          id: "tos-6",
          heading: "6. Governing Law",
          content: "These Terms of Service and all related engagements are governed by and construed in accordance with the laws of the State of Texas and applicable United States federal law, without regard to conflict of law principles.",
        },
        {
          id: "tos-7",
          heading: "7. Contact Information",
          content: "For questions regarding these Terms of Service, please reach out to our office:",
        },
      ],
    },
    privacyPolicy: {
      title: "Privacy Policy",
      badge: "Legal & Compliance",
      lastUpdated: "September 2026",
      sections: [
        {
          id: "priv-1",
          heading: "1. Commitment to Client Confidentiality",
          content: "At VR Tax CPA LLC, protecting your personal, tax, and financial privacy is one of our highest responsibilities. We adhere to the strictest ethical standards regarding client data security and confidentiality in accordance with professional accountancy guidelines.",
        },
        {
          id: "priv-2",
          heading: "2. Information We Collect & Submission via Secure Portal",
          content: "Please note that we do not collect or allow clients to upload confidential tax organizers, financial statements, or sensitive tax documents directly through this public marketing website. All document exchanges, tax organizers, questionnaires, and confidential client uploads are conducted exclusively through our secure, encrypted TaxDome Client Portal.\n\nTo provide comprehensive tax compliance, accounting, bookkeeping, payroll, and advisory services, we collect non-public personal information (NPI) exclusively through secure authorized channels (including TaxDome, direct consultations, or signed agreements), which may include:\n\n• Information provided on tax organizers, applications, and intake questionnaires submitted through TaxDome (e.g., name, address, Social Security Number, Employer Identification Number, dates of birth).\n• Financial documents uploaded securely via TaxDome for tax preparation (e.g., W-2s, 1099s, K-1s, bank statements, profit and loss reports, balance sheets).\n• Information regarding your business transactions, payroll data, and past tax filing history.\n• General inquiries submitted via our website contact form (limited to your name, email, phone number, and brief message).\n• Communications via email, phone, secure TaxDome portal, or virtual consultations.",
        },
        {
          id: "priv-3",
          heading: "3. How We Use & Protect Your Information",
          content: "We use your personal and financial information solely to deliver the services you have engaged us for, including:\n\n• Preparing federal, state, and local tax returns.\n• Providing ongoing accounting, bookkeeping, and payroll support.\n• Representing you before the Internal Revenue Service (IRS) or state tax authorities.\n• Advising on strategic tax minimization and business entity structuring.\n\nWe maintain physical, electronic, and procedural safeguards that comply with federal regulations and IRS Publication 4557 (Safeguarding Taxpayer Data) to guard your non-public personal information.",
        },
        {
          id: "priv-4",
          heading: "4. Third-Party Disclosure Policy",
          content: "We do not sell, rent, or trade your personal or financial information to any third party under any circumstances. Information is only shared with secure third-party software providers (e.g., TaxDome Client Portal, professional tax preparation platforms) necessary to perform agreed-upon functions, or when required by lawful subpoena or court order.",
        },
        {
          id: "priv-5",
          heading: "5. Use of Third-Party Service Providers",
          content: "To deliver professional tax, accounting, bookkeeping, payroll, and advisory services, VR Tax CPA LLC may utilize secure third-party platforms and service providers. These providers assist with functions such as tax preparation software, document storage, e-signature processing, payroll systems, and secure client communication. All third-party tools are selected for their security standards and are used solely to support the services you have engaged us for.",
        },
        {
          id: "priv-6",
          heading: "6. Contact Us Regarding Your Privacy",
          content: "If you have any questions or concerns regarding this Privacy Policy or our data security practices, please contact us:",
        },
      ],
    },
    disclaimer: {
      title: "Professional Disclaimer",
      badge: "Important Notices",
      lastUpdated: "September 2026",
      sections: [
        {
          id: "disc-1",
          heading: "1. No CPA-Client Relationship Formed by Website Use",
          content: "The information provided on this website (vrtaxcpa.com), including articles, blog posts, tax deadline guides, calculators, and social media content, is published for general informational and educational purposes only. Browsing this website, submitting an inquiry form, or reading our published materials does not establish a CPA-client, attorney-client, or fiduciary relationship between you and VR Tax CPA LLC.",
        },
        {
          id: "disc-2",
          heading: "2. Not Formal Tax, Legal, or Financial Advice",
          content: "Tax laws and regulations (both federal and state) are constantly evolving and vary substantially based on individual circumstances, entity classifications, and jurisdictions. Content on this site should not be relied upon as a substitute for individualized professional advice tailored to your specific tax situation. Always consult with a qualified professional before making tax, financial, or corporate entity decisions.",
        },
        {
          id: "disc-3",
          heading: "3. IRS Circular 230 Disclosure",
          content: "Pursuant to Internal Revenue Service (IRS) regulations, any tax information contained in this communication (including any attachments or website postings) is not intended or written to be used, and cannot be used, for the purpose of avoiding tax-related penalties under the Internal Revenue Code, or for promoting, marketing, or recommending to another party any tax-related transaction or matter.",
        },
        {
          id: "disc-4",
          heading: "4. Third-Party Platforms, Links & Tools",
          content: "This website may contain links to external third-party websites or services. VR Tax CPA LLC does not control and is not responsible for the accuracy, content, or privacy policies of third-party platforms.\n\nTo deliver professional tax, accounting, bookkeeping, payroll, and advisory services, VR Tax CPA LLC may utilize secure third-party platforms and service providers (such as TaxDome for client portal and document management, tax preparation software, e-signature processing, and payroll systems). All confidential tax organizers, financial statements, and client documents are collected and handled exclusively through our secure TaxDome portal and are never uploaded directly to this public website.",
        },
        {
          id: "disc-5",
          heading: "5. Contact Us",
          content: "For official professional consultations and formal advisory engagements, please contact:",
        },
      ],
    },
  },
};
