export const servicesData = {
  "tax-compliance": {
    slug: "tax-compliance",
    title: "Tax Compliance",
    primaryKeyword: "tax compliance tax return filing Irving TX",
    overviewTitle: "Accurate & Timely Tax Return Filing for Individuals and Businesses",
    overview: "We handle accurate and timely federal and Texas tax return preparation and filing for individuals and businesses, with careful attention to compliance and detail.",
    whatWeOffer: [
      { title: "Individual Tax Returns (1040)", desc: "Accurate preparation and e-filing of federal and state individual income tax returns, including rental income, self-employment, and investment reporting." },
      { title: "Business Tax Returns", desc: "Complete preparation of S-Corp (1120-S), C-Corp (1120), Partnership (1065), and LLC returns with a focus on compliance and accuracy." },
      { title: "Trust & Estate Returns (1041)", desc: "Filing for trusts, estates, and fiduciaries ensuring compliance with income distribution and beneficiary reporting requirements." },
      { title: "Non-Profit & Exempt Organizations (990)", desc: "Preparation of Form 990/990-EZ/990-N for non-profit and exempt organizations to maintain tax-exempt standing." },
    ],
    benefits: [
      { title: "Timely Filing & Compliance", desc: "We track federal and state filing deadlines to keep your returns submitted on time." },
      { title: "Thorough Deduction Review", desc: "Our thorough review ensures allowable deductions and credits are properly accounted for." },
      { title: "Reviewed by Our Expert Team", desc: "Every return is reviewed with care by our experienced team of tax professionals." },
      { title: "Organized Documentation", desc: "We maintain clear digital copies of your tax filings and support for your records." },
    ],
    process: [
      { num: "01", title: "Document Collection", desc: "We provide a clear checklist and securely collect all required financial documents, W-2s, 1099s, and business records." },
      { num: "02", title: "Review & Analysis", desc: "Our team reviews your financial documents, identifying allowable deductions, credits, and filing requirements." },
      { num: "03", title: "Preparation & Verification", desc: "We prepare your return using professional tax software, cross-checking for accuracy and compliance." },
      { num: "04", title: "Filing & Delivery", desc: "Returns are e-filed and you receive a complete copy along with a summary of your tax position." },
    ],
    industries: ["Real Estate & Rental Properties", "Restaurants & Hospitality", "Dental Practices", "IT Services & Tech Startups", "Staffing Companies", "Manufacturing", "Contractors & Construction", "Artists & Creators"],
    documents: [
      "W-2s, 1099s, and K-1 forms",
      "Prior year tax returns",
      "Business income and expense records",
      "Mortgage interest and property tax statements",
      "Retirement account contribution records",
      "Charitable donation receipts",
    ],
    faqs: [
      { q: "What types of returns does VR Tax CPA LLC file?", a: "We file individual (1040), S-Corp (1120-S), C-Corp (1120), Partnership (1065), LLC, Trust/Estate (1041), Non-Profit (990), and applicable state income tax returns." },
      { q: "What is the filing deadline for individual taxes?", a: "The standard federal deadline is April 15. We can file extensions to October 15 when needed, but tax liabilities remain due April 15." },
      { q: "Do you handle multi-state tax returns?", a: "We handle state return filings for individuals and business entities requiring multi-jurisdiction reporting." },
      { q: "How do I send my documents securely?", a: "We use a secure client portal for all document uploads and communication to protect your confidential financial information." },
      { q: "What if I haven't filed taxes in several years?", a: "We can help you prepare prior-year returns to bring your filings up to date with the IRS." },
      { q: "Do I owe state income tax in Texas?", a: "Texas has no individual state income tax. Certain businesses may be subject to the Texas Franchise Tax." },
    ],
    related: ["tax-planning", "irs-representation", "bookkeeping"],
    uniqueData: {
      checklist: [
        "All income statements (W-2, 1099, K-1) gathered",
        "Prior year return reviewed for carryovers",
        "Business expense categories organized",
        "Rental income and expense records documented",
        "Retirement contributions verified",
      ],
      calendar: [
        { date: "Jan 31", task: "W-2 & 1099 Form Filing Deadline" },
        { date: "Mar 15", task: "S-Corp & Partnership Return Deadline" },
        { date: "Apr 15", task: "Individual & C-Corp Return Deadline" },
        { date: "Oct 15", task: "Extended Individual Return Deadline" },
      ],
    },
  },

  "tax-planning": {
    slug: "tax-planning",
    title: "Tax Planning & Advisory",
    primaryKeyword: "tax planning advisory Irving TX business tax strategy",
    overviewTitle: "Proactive Tax Planning to Support Your Financial Goals",
    overview: "We provide proactive tax planning based on your income, business structure, and financial situation to help you make informed decisions and prepare for upcoming tax obligations.",
    whatWeOffer: [
      { title: "Year-Round Tax Strategy", desc: "Ongoing advisory throughout the year to help you prepare for estimated tax deadlines and evaluate potential deductions." },
      { title: "Entity Structure Advisory", desc: "Evaluation of business structures (LLC, S-Corp, C-Corp) to determine tax implications for your situation." },
      { title: "Estimated Tax Calculations", desc: "Help calculating quarterly estimated tax payments to avoid underpayment penalties." },
      { title: "Retirement Contribution Planning", desc: "Guidance on utilizing tax-advantaged retirement accounts such as SEP-IRA, Solo 401(k), and SIMPLE IRA." },
    ],
    benefits: [
      { title: "Proactive Planning", desc: "Stay ahead of tax deadlines with planned reviews and timely payment estimates." },
      { title: "Tailored Guidance", desc: "Every strategy is tailored to your business model, entity type, and financial circumstances." },
      { title: "Structured Approach", desc: "Clear recommendations covering entity options, deductions, and contribution timings." },
      { title: "Ongoing Support", desc: "Dedicated support to answer tax questions and navigate tax rule updates throughout the year." },
    ],
    process: [
      { num: "01", title: "Study the Given Situation", desc: "Comprehensive review of prior year tax returns, income sources, investments, and business structure to identify opportunities and issues." },
      { num: "02", title: "Strategy Development", desc: "Identify opportunities across entity structure, retirement contributions, deductions, and income timing strategies." },
      { num: "03", title: "Implementation Support", desc: "Guide you through action steps such as retirement account setup or entity election adjustments." },
      { num: "04", title: "Periodic Review", desc: "Periodic check-ins and mid-year reviews to adjust estimates as your business numbers evolve." },
    ],
    industries: ["Real Estate Investors", "Dental Practices", "IT Services & Consultants", "Restaurants & Hospitality", "Contractors", "Staffing Companies", "Manufacturing"],
    documents: [
      "Prior year tax returns",
      "Current year income projections",
      "Business profit & loss statements",
      "Investment and brokerage statements",
      "Retirement account balances and contribution history",
    ],
    faqs: [
      { q: "When should I begin tax planning?", a: "Tax planning is most effective when done proactively throughout the year, rather than waiting until tax season." },
      { q: "Should I form an S-Corp for my business?", a: "An S-Corp election may offer payroll tax advantages once business net income reaches consistent levels. We review your specific financial numbers to assess suitability." },
      { q: "What retirement plans can self-employed individuals set up?", a: "Self-employed individuals often utilize SEP-IRAs, Solo 401(k) plans (up to the annual IRS limit of $70,000 for 2026, plus age 50+ catch-up), or SIMPLE IRAs." },
      { q: "How do quarterly estimated tax payments work?", a: "Estimated tax payments are typically due in April, June, September, and January. We help calculate recommended payment amounts based on your projected earnings." },
    ],
    related: ["tax-compliance", "business-formation", "fractional-cfo"],
    uniqueData: {
      tips: [
        { category: "Entity Selection", tip: "Evaluate S-Corp status when business earnings support a reasonable owner salary alongside profit distributions." },
        { category: "Retirement", tip: "Consider maximizing a Solo 401(k) or SEP-IRA to shelter eligible self-employment income while building retirement assets." },
        { category: "Recordkeeping", tip: "Maintain detailed logs of business vehicle mileage and home office usage for allowable deductions." },
      ],
      deadlines: [
        { date: "April 15", event: "Q1 Estimated Tax Payment Due" },
        { date: "June 15", event: "Q2 Estimated Tax Payment Due" },
        { date: "September 15", event: "Q3 Estimated Tax Payment Due" },
        { date: "January 15", event: "Q4 Estimated Tax Payment Due" },
      ],
    },
  },

  "business-formation": {
    slug: "business-formation",
    title: "Business Entity Formation",
    primaryKeyword: "business entity formation LLC S-Corp Irving TX",
    overviewTitle: "Set Up Your Business Entity with the Right Tax Structure",
    overview: "We provide guidance on business entity structure, Texas filings, Federal EIN registration, and S-Corp election filings to help you establish your business with the appropriate tax structure.",
    whatWeOffer: [
      { title: "Entity Selection Guidance", desc: "Advisory on choosing between Sole Proprietor, LLC, S-Corp, C-Corp, or Partnership based on your tax and operational goals." },
      { title: "Texas State Filings", desc: "Preparation and electronic submission of formation documents with the Texas Secretary of State and Registered Agent setup guidance." },
      { title: "Federal EIN Registration", desc: "Assistance with obtaining your Federal Employer Identification Number (EIN) for banking and tax filings." },
      { title: "S-Corp Election (Form 2553)", desc: "Timely preparation and filing of IRS Form 2553 to elect S-Corporation status within the required statutory window." },
    ],
    benefits: [
      { title: "Liability Separation", desc: "Proper entity registration establishes formal separation between your business and personal affairs." },
      { title: "Tax Efficiency", desc: "Selecting the appropriate entity classification helps optimize your tax obligations from inception." },
      { title: "Business Credibility", desc: "A formal registered entity enhances credibility with banks, vendors, and clients." },
      { title: "Solid Foundation", desc: "Setting up your accounts and tax elections correctly from the beginning prevents costly reorganizations later." },
    ],
    process: [
      { num: "01", title: "Discovery & Entity Review", desc: "Understand your ownership structure, business model, projected revenue, and operational plans." },
      { num: "02", title: "Entity Recommendation", desc: "Recommend the appropriate entity structure and tax classification for your situation." },
      { num: "03", title: "State & Federal Filings", desc: "Prepare and file formation certificates with the Texas Secretary of State and obtain your Federal EIN." },
      { num: "04", title: "Financial Setup Guidance", desc: "Provide guidance on business banking, recordkeeping, and accounting system setup if needed." },
    ],
    industries: ["IT Services & Freelancers", "Dental Practices", "Contractors & Trades", "Real Estate Investors", "Restaurants", "Staffing Companies", "Manufacturing"],
    documents: [
      "Owner identification information (SSN or ITIN)",
      "Proposed entity name and principal address",
      "Ownership breakdown and percentages",
      "Nature of business activities",
    ],
    faqs: [
      { q: "Should I form an LLC or elect S-Corp status?", a: "An LLC offers legal flexibility and liability protection. An S-Corp election on top of an LLC may provide payroll tax advantages once net earnings reach consistent levels." },
      { q: "How long does Texas LLC formation take?", a: "The Texas Secretary of State typically processes filings within several business days depending on state processing volumes." },
      { q: "What is an EIN and why is it needed?", a: "An Employer Identification Number (EIN) is your federal business tax ID, required to open commercial bank accounts and file business tax returns." },
      { q: "When must the S-Corp election (Form 2553) be filed?", a: "For new entities, Form 2553 must be filed within 2½ months (75 days) of formation. For existing entities, it must be filed by March 15th of the tax year it is to take effect." },
    ],
    related: ["tax-planning", "payroll-services", "accounting-services"],
    uniqueData: {
      checklist: [
        "Entity name availability confirmed with Texas SOS",
        "Entity type selected based on tax advisory",
        "Registered agent designated",
        "Federal EIN obtained from the IRS",
        "Business bank account established",
      ],
      calendar: [
        { date: "Step 1", task: "Texas SOS Entity Formation Filing" },
        { date: "Step 2", task: "Federal EIN Obtainment & Banking Setup" },
        { date: "Within 2½ Months", task: "S-Corp Election Filing (Form 2553) within 2½ months of forming or by March 15th for an existing entity" },
        { date: "Initial Period", task: "Accounting System & Payroll Setup (if needed)" },
      ],
    },
  },

  "payroll-services": {
    slug: "payroll-services",
    title: "Payroll Support",
    primaryKeyword: "payroll setup training small business payroll Irving TX",
    overviewTitle: "Payroll Setup & Management Training for Small Businesses",
    overview: "We help you set up and manage payroll platforms by providing proper configuration, tax withholding guidance, and team training. We focus on setup and training rather than direct payroll processing.",
    whatWeOffer: [
      { title: "Payroll Partner Account Setup", desc: "Initial configuration of your payroll account on platforms such as Gusto or QuickBooks, including company info, direct deposit, and tax configuration." },
      { title: "Employee & Contractor Onboarding", desc: "Guidance on properly collecting W-4 and W-9 forms and adding team members to the payroll system." },
      { title: "Payroll Training & Workflow Setup", desc: "Step-by-step training on how to enter hours, run payroll, and track tax reports within your software." },
      { title: "S-Corp Reasonable Salary Guidance", desc: "Advisory on determining appropriate reasonable salary benchmarks for S-Corp owner-employees." },
    ],
    benefits: [
      { title: "Proper Initial Configuration", desc: "Ensure your state and federal payroll tax accounts and withholding settings are configured correctly from day one." },
      { title: "Self-Sufficient Management", desc: "Gain the confidence and training needed to run and manage payroll smoothly within your organization." },
      { title: "Worker Classification Guidance", desc: "Guidance on distinguishing between W-2 employees and 1099 contractors to support compliant operations." },
      { title: "Expert Advisory Support", desc: "Access to our team for questions regarding payroll setup and owner compensation rules." },
    ],
    process: [
      { num: "01", title: "Payroll Needs Review", desc: "Review your team structure, pay schedule, and compensation model to select the appropriate platform settings." },
      { num: "02", title: "Platform Setup", desc: "Configure your payroll partner account with company details, tax registration numbers, and pay frequencies." },
      { num: "03", title: "Employee Onboarding Assistance", desc: "Assist with employee W-4 setup and direct deposit configurations." },
      { num: "04", title: "Training & Handover", desc: "Conduct walkthrough training so you can manage ongoing payroll runs independently and accurately." },
    ],
    industries: ["Restaurants & Hospitality", "Dental Practices", "Staffing Companies", "Contractors & Construction", "IT Services", "Manufacturing", "Real Estate Firms"],
    documents: [
      "Employer EIN and Texas state employer tax numbers",
      "Employee W-4 forms and direct deposit info",
      "Contractor W-9 forms",
      "Pay schedule and compensation details",
    ],
    faqs: [
      { q: "Do you process payroll runs on an ongoing basis?", a: "No. We provide payroll setup, configuration, and training through payroll software partners (like Gusto or QuickBooks). You or your team will execute regular pay runs directly on the platform." },
      { q: "What is the difference between an employee and a contractor?", a: "The IRS evaluates behavioral control, financial control, and the type of relationship to determine worker status. We provide guidance to help ensure proper classification." },
      { q: "What is reasonable compensation for an S-Corp owner?", a: "The IRS requires active S-Corp shareholders who provide services to receive a reasonable W-2 wage subject to payroll taxes. We advise on benchmarking reasonable salary figures." },
    ],
    related: ["business-formation", "accounting-services", "tax-compliance"],
    uniqueData: {
      checklist: [
        "Federal EIN and state employer accounts active",
        "Payroll software account configured",
        "Employee W-4 and direct deposit details added",
        "Pay frequency and schedules established",
        "Initial test payroll walkthrough completed",
      ],
      calendar: [
        { date: "Setup Period", task: "Platform Configuration & Employee Onboarding" },
        { date: "Training", task: "Payroll Walkthrough & Admin Training" },
        { date: "Year-End", task: "Annual W-2 and 1099 Generation Review" },
      ],
    },
  },

  "accounting-services": {
    slug: "accounting-services",
    title: "Accounting Services",
    primaryKeyword: "accounting services bookkeeping Irving TX small business",
    overviewTitle: "Accurate Accounting & Bookkeeping for Clear Financial Management",
    overview: "We provide monthly and quarterly accounting support to maintain accurate financial records and prepare clear management financials for your business.",
    whatWeOffer: [
      { title: "Monthly & Quarterly Bookkeeping", desc: "Accurate categorization of business transactions, expense tracking, and regular bank and credit card reconciliations." },
      { title: "Management Financial Statements", desc: "Preparation of internal management financial statements (Profit & Loss, Balance Sheet) for business owners." },
      { title: "Accounts Reconciliation", desc: "Systematic reconciliation of bank and credit accounts to ensure clean, balanced general ledgers." },
      { title: "Year-End Financial Organization", desc: "Year-end reconciliation and clean-up to ensure your financial records are complete for tax return preparation." },
    ],
    benefits: [
      { title: "Clear Financial View", desc: "Gain visibility into your business income, expenses, and cash flow trends." },
      { title: "Tax-Ready Records", desc: "Well-maintained books make annual tax return filing faster, smoother, and more accurate." },
      { title: "Reviewed by Our Expert Team", desc: "Your accounts are reviewed by experienced accounting professionals for quality and consistency." },
      { title: "Management Insights", desc: "Internal management reports provide useful data for budgeting and operational decisions." },
    ],
    process: [
      { num: "01", title: "Books Assessment", desc: "Review your existing accounting software, chart of accounts, and financial records." },
      { num: "02", title: "System Configuration & Cleanup", desc: "Set up or clean up your accounting file and establish a structured chart of accounts." },
      { num: "03", title: "Ongoing Bookkeeping Cycle", desc: "Regularly import transactions, reconcile accounts, and identify any discrepancies." },
      { num: "04", title: "Review & Reporting", desc: "Provide management summary reports and maintain organized records for year-end review." },
    ],
    industries: ["Restaurants & Hospitality", "Real Estate & Property Management", "Dental Practices", "IT Services & Consultants", "Contractors", "Staffing Companies", "Manufacturing", "Artists & Creatives"],
    documents: [
      "Bank and credit card statements",
      "Sales reports and revenue summaries",
      "Expense receipts and vendor bills",
      "Access to accounting software (QuickBooks Online, QuickBooks Desktop, or Sage)",
    ],
    faqs: [
      { q: "What accounting software platforms do you support?", a: "We primarily work with QuickBooks Online, QuickBooks Desktop, and Sage." },
      { q: "What is the difference between bookkeeping and management accounting?", a: "Bookkeeping involves recording and reconciling daily financial transactions. Management accounting focuses on organizing that data into financial statements for internal business planning." },
      { q: "Can you help clean up backlogged or disorganized books?", a: "Yes. We assist with bookkeeping catch-up and cleanup services to bring un-reconciled records up to date." },
    ],
    related: ["tax-compliance", "fractional-cfo", "payroll-services"],
    uniqueData: {
      checklist: [
        "Chart of accounts customized for your industry",
        "Bank and credit card feeds connected and reconciled",
        "Historical transactions categorized",
        "Accounts reconciliation completed",
        "Internal management report templates configured",
      ],
      calendar: [
        { date: "Monthly / Quarterly", task: "Account Reconciliation & Ledger Updates" },
        { date: "Year-End", task: "Year-End Account Closing & Tax Prep Package Delivery" },
      ],
    },
  },

  "fractional-cfo": {
    slug: "fractional-cfo",
    title: "Fractional CFO Services",
    primaryKeyword: "fractional CFO financial advisory Irving TX strategic advisory",
    overviewTitle: "Strategic Financial Guidance for Growing Businesses",
    overview: "We provide flexible financial guidance, cash flow planning, and budgeting support to help growing businesses understand their numbers and make informed decisions.",
    whatWeOffer: [
      { title: "Financial Forecasting & Budgeting", desc: "Build dynamic cash flow projections and annual budgets to help guide business decisions." },
      { title: "KPI Dashboard & Performance Tracking", desc: "Identify key financial metrics to monitor performance, margin trends, and expense ratios." },
      { title: "Strategic Advisory Sessions", desc: "Periodic review sessions discussing pricing structure, operational costs, and capital allocation." },
      { title: "Internal Management Modeling", desc: "Custom financial modeling to support internal planning, break-even analysis, and resource budgeting." },
    ],
    benefits: [
      { title: "High-Level Financial Guidance", desc: "Access strategic financial insight without the overhead of a full-time executive." },
      { title: "Cash Flow Visibility", desc: "Anticipate cash needs and plan working capital proactively." },
      { title: "Reviewed by Our Expert Team", desc: "Benefit from seasoned financial professionals analyzing your numbers." },
      { title: "Data-Driven Decisions", desc: "Make informed business choices backed by clear financial trends and forecasts." },
    ],
    process: [
      { num: "01", title: "Financial Diagnostic", desc: "Review your historical numbers, cost structure, margins, and operational model." },
      { num: "02", title: "Model & Roadmap Design", desc: "Develop custom financial models, budgeting frameworks, and target KPIs." },
      { num: "03", title: "System Implementation", desc: "Establish regular tracking cadences and dashboard views for key metrics." },
      { num: "04", title: "Ongoing Advisory", desc: "Conduct regular financial review meetings to evaluate actual performance against plan." },
    ],
    industries: ["IT Services & SaaS Startups", "Dental Practices & Healthcare", "Restaurants & Franchise", "Real Estate & Property Development", "Staffing Companies", "Manufacturing", "Contractors"],
    documents: [
      "Recent financial statements and ledgers",
      "Current revenue and expense run-rates",
      "Existing budgets or projections (if available)",
      "Key vendor and debt obligation summaries",
    ],
    faqs: [
      { q: "What does a Fractional CFO do?", a: "A Fractional CFO provides forward-looking financial advisory, cash flow forecasting, budgeting, and performance analysis on a part-time or advisory basis." },
      { q: "Do you issue audited or compiled financials for third parties?", a: "No. We provide internal management advisory services only. We do not provide attest, audit, or compilation services for third parties or lenders." },
      { q: "How are Fractional CFO advisory sessions structured?", a: "Advisory sessions are tailored to your needs, typically conducted monthly or quarterly to review financial performance, update forecasts, and address strategic questions." },
    ],
    related: ["accounting-services", "tax-planning", "business-formation"],
    uniqueData: {
      tips: [
        { category: "Cash Flow", tip: "Maintain a rolling 13-week cash forecast to manage working capital smoothly." },
        { category: "Margin Analysis", tip: "Regularly evaluate gross margins across key product and service lines." },
      ],
      deadlines: [
        { date: "Monthly", event: "Internal Performance Review & Dashboard Update" },
        { date: "Quarterly", event: "Forecast vs. Actual Variance Review" },
        { date: "Annually", event: "Annual Operating Budget Planning" },
      ],
    },
  },

  "irs-representation": {
    slug: "irs-representation",
    title: "IRS Representation",
    primaryKeyword: "IRS representation notice resolution tax help Irving TX",
    overviewTitle: "Professional Representation for Tax Notices and Inquiries",
    overview: "We assist with IRS and tax authority notices, handling communications and responses to help address back tax returns, notices, and tax resolution matters.",
    whatWeOffer: [
      { title: "Notice & Letter Response", desc: "Professional review and formal response to IRS and state tax notices and inquiry letters." },
      { title: "Audit & Examination Representation", desc: "Representation during correspondence and examination inquiries, communicating directly with tax agencies." },
      { title: "Unfiled Back Tax Returns", desc: "Preparation and filing of prior-year unfiled tax returns to bring your records into compliance." },
      { title: "Tax Resolution Assistance", desc: "Assistance negotiating Installment Agreements and penalty abatement requests where applicable." },
    ],
    benefits: [
      { title: "Direct Communication", desc: "We communicate directly with tax authorities on your behalf using appropriate authorization." },
      { title: "Strategic Case Management", desc: "Careful review of documentation and notice details to prepare thorough responses." },
      { title: "Experienced Guidance", desc: "Guidance from tax professionals familiar with IRS procedures and response timelines." },
      { title: "Restored Compliance", desc: "Structured approach to resolve back filings and establish current compliance." },
    ],
    process: [
      { num: "01", title: "Notice Review & Assessment", desc: "Carefully analyze the notice details, statutory deadlines, and underlying tax issues." },
      { num: "02", title: "Authorization (Form 2848)", desc: "File appropriate Power of Attorney forms so we can communicate directly with the IRS." },
      { num: "03", title: "Response & Documentation", desc: "Gather required financial records, prepare the formal response, and submit before deadlines." },
      { num: "04", title: "Case Resolution", desc: "Follow through with the tax authority until resolution is confirmed." },
    ],
    industries: ["Self-Employed & Freelancers", "Real Estate Investors", "Restaurants", "Contractors", "IT Services", "Manufacturing", "Artists & Creatives"],
    documents: [
      "All notices and letters received from the IRS or state (with dates)",
      "Copies of relevant prior-year tax returns",
      "Supporting documentation related to the items in question",
      "Prior correspondence records",
    ],
    faqs: [
      { q: "What should I do when I receive an IRS notice?", a: "Do not ignore it. Most notices have strict 30-day or 60-day response windows. Contact us promptly with a copy of the notice so we can determine the appropriate steps." },
      { q: "What is penalty abatement?", a: "The IRS may grant penalty relief under First-Time Abatement for eligible taxpayers with a clean filing history, or under Reasonable Cause for specific qualifying hardships." },
      { q: "Can you help if I haven't filed tax returns for several years?", a: "Yes. We assist in preparing and submitting unfiled back returns to help restore your standing with the IRS." },
    ],
    related: ["tax-compliance", "tax-planning", "accounting-services"],
    uniqueData: {
      checklist: [
        "Notice copies and deadlines logged",
        "IRS transcripts requested via Power of Attorney",
        "Supporting documentation organized",
        "Formal response drafted and submitted before deadline",
      ],
      calendar: [
        { date: "Immediate", task: "Notice Review & Response Deadline Identification" },
        { date: "Within 7-14 Days", task: "POA Submission & Transcript Analysis" },
        { date: "Before Due Date", task: "Formal Response Submission" },
      ],
    },
  },

  "sales-tax-1099": {
    slug: "sales-tax-1099",
    title: "Sales Tax & 1099 Filing",
    primaryKeyword: "Texas sales tax return filing 1099 filing Irving TX",
    overviewTitle: "Texas Sales Tax Return Filing & Annual 1099 Preparation",
    overview: "We prepare and file Texas sales tax returns and provide preparation and filing support for 1099 forms, including various payment types.",
    whatWeOffer: [
      { title: "Texas Sales Tax Return Filing", desc: "Accurate preparation and electronic filing of monthly, quarterly, or annual Texas sales and use tax returns." },
      { title: "Annual 1099 Preparation & Filing", desc: "Year-end preparation and electronic filing of 1099 forms (1099-NEC, 1099-MISC, 1099-DIV, 1099-INT) for contractors, rent, interest, and dividends." },
      { title: "1099 Recipient Delivery", desc: "Preparation and delivery of recipient copies by the January 31 deadline with complete electronic filing records." },
      { title: "W-9 Verification Assistance", desc: "Review of vendor and payee W-9 information to ensure valid Tax Identification Numbers (TINs) before filing." },
    ],
    benefits: [
      { title: "Timely Submission", desc: "Meet all Texas Comptroller and IRS reporting deadlines without last-minute stress." },
      { title: "Texas-Focused Filing", desc: "Specialized focus on Texas state and local sales tax reporting requirements." },
      { title: "Comprehensive 1099 Coverage", desc: "Accurate reporting for non-employee compensation, rent, interest, and dividend disbursements." },
      { title: "Direct IRS E-Filing", desc: "Electronic filing with the IRS and state authorities with full filing confirmations provided." },
    ],
    process: [
      { num: "01", title: "Data Collection", desc: "Gather total sales figures for sales tax returns, and annual payment ledgers with W-9 details for 1099 filings." },
      { num: "02", title: "Verification & Review", desc: "Reconcile payment totals and verify payee name and Tax ID information." },
      { num: "03", title: "Form Preparation", desc: "Prepare Texas sales tax returns and 1099 forms using professional tax software." },
      { num: "04", title: "Filing & Recipient Distribution", desc: "E-file returns with the Texas Comptroller and IRS, and distribute 1099 copies to recipients." },
    ],
    industries: ["Restaurants & Hospitality", "Real Estate & Property Managers", "Contractors", "IT Services & Consultants", "Staffing Companies", "Artists & Creatives", "Manufacturing"],
    documents: [
      "Gross sales and taxable sales summaries (for Texas sales tax)",
      "List of contractors and payees paid during the year (for 1099s)",
      "Completed W-9 forms for all payees",
      "Payment amounts broken down by category (services, rent, interest, dividends)",
    ],
    faqs: [
      { q: "What states do you file sales tax returns for?", a: "We file sales and use tax returns specifically for the state of Texas." },
      { q: "What types of 1099 forms do you file?", a: "We prepare and file 1099-NEC (non-employee compensation), 1099-MISC (rents, other income), 1099-DIV (dividends), and 1099-INT (interest payments)." },
      { q: "What is the deadline for filing 1099 forms?", a: "1099-NEC forms must be filed with the IRS and provided to recipients by January 31. Other 1099 forms must also be provided to recipients by January 31." },
      { q: "When are Texas sales tax returns due?", a: "Texas sales tax returns are generally due on the 20th day of the month following the end of the reporting period (monthly, quarterly, or annually)." },
    ],
    related: ["tax-compliance", "accounting-services", "payroll-services"],
    uniqueData: {
      checklist: [
        "Texas sales records and taxable sales amounts compiled",
        "All 1099-eligible payees identified (contractors, rent, interest, dividends)",
        "W-9 forms verified for each payee with matching TINs",
        "Sales tax and 1099 returns reviewed and e-filed",
      ],
      calendar: [
        { date: "January 31", task: "1099 Forms (1099-NEC, 1099-MISC, 1099-DIV, 1099-INT) Issued to Recipients & Filed" },
        { date: "20th of Each Month/Quarter", task: "Texas State & Local Sales Tax Return Due" },
        { date: "Year-Round", task: "W-9 Collection from New Vendors & Contractors" },
      ],
    },
  },
};
